### ISSUE TITLE
Big File Support

### ISSUE THREAD

**Issue by andrewyatz** [wtsi-web/Genoverse#10]
Native BigFile support such as:
- BigBed
- BigWig
- Tabix indexed files (block gzipped)
  - This includes VCF but could be rolled out to other tab delimited formats

**Comment by sourabh2k15** [comment]
I would love to contribute to this port for big file formats :+1:

**Comment by simonbrent** [comment]
I am happy to review pull requests

**Comment by sourabh2k15** [comment]
As a first step I have cloned the dalliance repo , trying to understand the js parser code. I hope I can produce something useful for this repo.

**Comment by sourabh2k15** [comment]
Just a thought : Can we compile the libBigWig C parser into JS using emscripten and use it to parse bigwig files on client side followed by our custom rendering logic that would display the data onto canvas ?

**Comment by andrewyatz** [comment]
I haven't had any experience of emscripten. I know that libBigWig uses libcurl and zlib. I don't know how these work with emscripten.

**Comment by sourabh2k15** [comment]
Even I haven't had much experience with emscripten other than knowing the fact that it is powerful and can convert any LLVM code to javascript which can be then executed in node environments or in the browser. I have tried it by converting simple C and C++ code to JS.

The examples of what have been already been ported over to javascript with emscripten, gave me confidence to think in this direction ( entire ffmpeg library ported to ffmpeg.js :1st_place_medal:  !! ) : 
https://github.com/kripken/emscripten/wiki/Porting-Examples-and-Demos

main website : http://kripken.github.io/emscripten-site/

This guy has tried porting htslib to javascript through emscripten : https://github.com/cmdcolin/htslib_emscripten. Will try to follow his work and compile htslib to js modules :).
htslib also uses zlib. Let me know if this is worth a try and your thoughts on this.

**Comment by andrewyatz** [comment]
I think it's worth a try though I'm not sure totally sure of the pros/cons
of doing this.
