### ISSUE TITLE
Persistent highlighting a region of the genome

### ISSUE THREAD

**Issue by andrewyatz** [wtsi-web/Genoverse#11]
UCSC released a new feature on the 4th March called *Genome Browser Highlight". The idea is you can drag select a region (holding shift & draw a region) and then choose to highlight it rather than zooming in. The highlight persists on multiple levels of zoom (if you zoom into the highlighted region then everything is highlighted).

They also support highlighting of a region based on a feature (it makes finding co-located features with a gene/transcript a lot easier).

**Comment by simonbrent** [comment]
Done - you can highlight with the region selection menu, or from a link in feature popups.

**Comment by andrewyatz** [comment]
That's really nice. Thanks :smile:

**Comment by simonbrent** [comment]
One problem: currently the only way to clear highlights is to refresh. I might consider adding a control somewhere, if I can work out where the best place in the UI would be.

**Comment by andrewyatz** [comment]
We don't really have the concept of right click in genoverse. Otherwise
right clicking on the region, offering a popup and then clearing from there
might be a way to do it. Otherwise it feels like it should move into the
right hand set of controls though that could get messy.

**Comment by simonbrent** [comment]
I refuse to override the browser's default right-click action, because whenever I use a website which does that I get really annoyed with it. I agree that adding it to the right hand side would probably be messy...maybe clicking on the text at the top of a highlighted region could give a menu to clear this/all highlights

**Comment by andrewyatz** [comment]
Very true I also get annoyed by that. Eventually will we need a menu bar
for moregenoverse features?

**Comment by simonbrent** [comment]
Maybe. Anyway, I've added remove this/all highlights in links in the menus when you click in the highlights' labels.

**Comment by AlgyTaylor** [comment]
> I refuse to override the browser's default right-click action

The right stance, IMO :+1:
