### ISSUE TITLE
Trix & BigTab Support

### ISSUE THREAD

**Issue by andrewyatz** [wtsi-web/Genoverse#12]
Trix is a free text search engine (http://genome.ucsc.edu/goldenPath/help/trix.html) developed by UCSC allowing you to search for values within a track and returning an ID in which that value was found. Their main use-case is in TrackHubs where a track can have a trix index attached using the searchTrix parameter. Supporting this and allowing searching of the trix index from Genoverse would be really cool.

BigTab is an attribute format from UCSC not yet released but should hold IDs to attribute lists. Once we have more information I will feed this back to you

**Comment by simonbrent** [comment]
Closed due to lack of activity
