### ISSUE TITLE
Mixing GRCh37 with GRCh38

### ISSUE THREAD

**Issue by senanu** [wtsi-web/Genoverse#25]
Hi, 

I noticed that the dbSNP track (Genoverse.Track.dbSNP) is showing SNPs in exons but calling them intronic snps. This is evident on the sample setup you maintain on genoverse.org. I think the problem is that you’ve hard-coded the ensembl GRCh37 build into the URL called by Genovese.Track.dbSNP. 

I suspect that this is a very easy fix, however, it might be a problem for other tracks that I haven’t seen yet. It is also very difficult to identify since we sort of trust that the features that we say are on a track really are there!

**Comment by simonbrent** [comment]
Argh, yes...good spot, I've fixed this now.

It should be pointed out that these tracks are all effectively examples of things you can do with Genoverse. They are easily configurable - in the case a track has data from an assembly you don't want, you can just override the track's URL to get data from a source you DO want (although in the case of that dbSNP track this was made more complicated by the fact that the populateMenu function also makes a request to the Ensembl REST API for data, and has links back to a particular version of Ensembl, so you'd have to override that function too).

Genoverse show a lot more types of data than just what is in this repo (see Decipher, for example: https://decipher.sanger.ac.uk/browser#q/BRCA2/location/13:32806708-33056708).
