### ISSUE TITLE
error while getting the data, see console for more details

### ISSUE THREAD

**Issue by jurivero** [wtsi-web/Genoverse#27]
Downloaded Genoverse and running on my computer I get the above error, do you know why this is happened. (in Ubuntu and Windows)
The error is that does not display the data in the sequences or genes
Thank you
Juan

**Comment by simonbrent** [comment]
You can access the console by pressing F12 in Chrome or Firefox. There will be an error message displayed there which should give more information about what is going wrong.

**Comment by jurivero** [comment]
Simon thank you for tour quick respond. I am trying to read bed files on this chart, do I have to have bed tools install also? or the Genoverse should read the files without any extra component installed such as bed tools?
I copied the error after I use the developer tool (F12) in Firefox to copy and paste. There is nothing that indicates where is it coming from

**Comment by simonbrent** [comment]
Can you please paste the error here?

**Comment by jurivero** [comment]
error while getting the data, see console for more details

**Comment by jurivero** [comment]
![errors](https://cloud.githubusercontent.com/assets/13647324/10135468/30900a36-65bc-11e5-916c-349873f6c057.jpg)

**Comment by simonbrent** [comment]
Ok, that is rather strange. Is this just the unmodified code currently available on github on the gh-pages branch?

**Comment by ens-hsr** [comment]
The console isn't showing JS warnings.

**Comment by simonbrent** [comment]
Ah, that is true! The JS button is light, which only happens when it has been disabled.

**Comment by jurivero** [comment]
what is that mean?

**Comment by jurivero** [comment]
This the code that is in gh-pages correct, just download it and run it

**Comment by jurivero** [comment]
Am I Missing anything that needs to be downloaded and install to get these errors gone?

**Comment by simonbrent** [comment]
In your screenshot there are a number of headings in the console: Net, CSS, JS, Security, Logging.
The JS heading is a different colour to the others, implying that javascript warnings are being hidden. If you click on the little arrow on the JS heading, you should see two checkboxes, for Errors and Warnings. If they do not have ticks next to them, you won't see the errors. Ensure they have ticks next to them (click on them if necessary), and reload the page. Hopefully at that point you will see an error message in the console.

**Comment by jurivero** [comment]
file:///C:/Users/brt/xsl/tysl/578/Genoverse-gh-pages/examples/genoverse.org/styles.css
file:///C:/Users/brt/xsl/tysl/578/Genoverse-gh-pages/js/genoverse.combined.js
reflow: 0.36ms
reflow: 0.67ms
GET 
https://s3.amazonaws.com/github/ribbons/forkme_right_orange_ff7600.png [HTTP/1.1 304 Not Modified 355ms]
reflow: 0.16ms function .offset, genoverse.combined.js line 6
reflow: 0.19ms function EventLoop.prototype.enter, script.js line 339
This site makes use of a SHA-1 Certificate; it's recommended you use certificates with signature algorithms that use hash functions stronger than SHA-1.[Learn More] s3.amazonaws.com
file:///C:/Users/brt/xsl/tysl/578/Genoverse-gh-pages/css/genoverse.css
reflow: 0.14ms
file:///C:/Users/brt/xsl/tysl/578/Genoverse-gh-pages/css/font-awesome.css
file:///C:/Users/brt/xsl/tysl/578/Genoverse-gh-pages/css/fileDrop.css
file:///C:/Users/brt/xsl/tysl/578/Genoverse-gh-pages/css/tooltips.css
file:///C:/Users/brt/xsl/tysl/578/Genoverse-gh-pages/css/fullscreen.css
file:///C:/Users/brt/xsl/tysl/578/Genoverse-gh-pages/css/resizer.css
file:///C:/Users/brt/xsl/tysl/578/Genoverse-gh-pages/css/trackControls.css
file:///C:/Users/brt/xsl/tysl/578/Genoverse-gh-pages/css/karyotype.css
file:///C:/Users/brt/xsl/tysl/578/Genoverse-gh-pages/css/controlPanel.css
Unknown property 'user-select'.  Declaration dropped. genoverse.css:16:13
Error in parsing value for 'background-image'.  Declaration dropped. genoverse.css:161:20
syntax error grch38.js:1:1
reflow: 0.61ms
syntax error controlPanel.js:1:1
syntax error karyotype.js:1:1
syntax error trackControls.js:1:1
syntax error resizer.js:1:1
syntax error focusRegion.js:1:1
syntax error fullscreen.js:1:1
not well-formed tooltips.js:1:1
syntax error fileDrop.js:1:1
reflow: 0.19ms function Ib, genoverse.combined.js line 5
reflow: 0.44ms function Ib, genoverse.combined.js line 5
reflow: 0.19ms function .offset, genoverse.combined.js line 6
reflow: 0.28ms function Ib, genoverse.combined.js line 5
reflow: 0.09ms function .reliableMarginRight, genoverse.combined.js line 5
reflow: 0.05ms function xb, genoverse.combined.js line 5
reflow: 0.32ms function Ib, genoverse.combined.js line 5
file:///C:/Users/brt/xsl/tysl/578/Genoverse-gh-pages/i/Grabbar.png
file:///C:/Users/brt/xsl/tysl/578/Genoverse-gh-pages/i/Grabbar.png
reflow: 0.35ms function Ib, genoverse.combined.js line 5
file:///C:/Users/brt/xsl/tysl/578/Genoverse-gh-pages/i/auto_height.png
file:///C:/Users/brt/xsl/tysl/578/Genoverse-gh-pages/i/auto_height.png
reflow: 0.38ms function Ib, genoverse.combined.js line 5
reflow: 0.26ms function EventLoop.prototype.enter, script.js line 339
Unknown property '-moz-osx-font-smoothing'.  Declaration dropped. font-awesome.css:20:25
Expected 'none', URL, or filter function but found 'progid'.  Error in parsing value for 'filter'.  Declaration dropped. font-awesome.css:109:10
reflow: 0.35ms function Ib, genoverse.combined.js line 5
reflow: 0.39ms function Ib, genoverse.combined.js line 5
reflow: 0.28ms function Ib, genoverse.combined.js line 5
reflow: 0.2ms function Ib, genoverse.combined.js line 5
Expected 'none', URL, or filter function but found 'progid'.  Error in parsing value for 'filter'.  Declaration dropped. font-awesome.css:115:10
Expected 'none', URL, or filter function but found 'progid'.  Error in parsing value for 'filter'.  Declaration dropped. font-awesome.css:121:10
Expected 'none', URL, or filter function but found 'progid'.  Error in parsing value for 'filter'.  Declaration dropped. font-awesome.css:127:10
reflow: 0.33ms function Ib, genoverse.combined.js line 5
Expected 'none', URL, or filter function but found 'progid'.  Error in parsing value for 'filter'.  Declaration dropped. font-awesome.css:133:10
reflow: 0.08ms function Ib, genoverse.combined.js line 5
reflow: 0.27ms function Ib, genoverse.combined.js line 5
reflow: 0.42ms function Ib, genoverse.combined.js line 5
reflow: 0.18ms function Ib, genoverse.combined.js line 5
reflow: 0.38ms function Ib, genoverse.combined.js line 5
reflow: 0.18ms function Ib, genoverse.combined.js line 5
reflow: 0.41ms function Ib, genoverse.combined.js line 5
reflow: 0.16ms function Ib, genoverse.combined.js line 5
reflow: 0.38ms function Ib, genoverse.combined.js line 5
reflow: 0.26ms function Ib, genoverse.combined.js line 5
reflow: 0.49ms function Ib, genoverse.combined.js line 5
reflow: 0.07ms function Ib, genoverse.combined.js line 5
reflow: 0.26ms function Ib, genoverse.combined.js line 5
reflow: 0.07ms function Ib, genoverse.combined.js line 5
reflow: 0.27ms function Ib, genoverse.combined.js line 5
reflow: 0.07ms function Ib, genoverse.combined.js line 5
reflow: 0.28ms function Ib, genoverse.combined.js line 5
reflow: 0.17ms function Ib, genoverse.combined.js line 5
reflow: 0.14ms function Ib, genoverse.combined.js line 5
reflow: 0.15ms function Ib, genoverse.combined.js line 5
reflow: 0.13ms function Ib, genoverse.combined.js line 5
reflow: 0.2ms function Ib, genoverse.combined.js line 5
reflow: 0.13ms function Ib, genoverse.combined.js line 5
reflow: 0.15ms function Ib, genoverse.combined.js line 5
reflow: 0.41ms function Ib, genoverse.combined.js line 5
reflow: 0.15ms function Ib, genoverse.combined.js line 5
reflow: 0.39ms function Ib, genoverse.combined.js line 5
reflow: 0.23ms function Ib, genoverse.combined.js line 5
reflow: 0.13ms function Ib, genoverse.combined.js line 5
reflow: 0.15ms function Ib, genoverse.combined.js line 5
reflow: 0.13ms function Ib, genoverse.combined.js line 5
reflow: 0.17ms function Ib, genoverse.combined.js line 5
reflow: 0.13ms function Ib, genoverse.combined.js line 5
reflow: 0.15ms function Ib, genoverse.combined.js line 5
reflow: 0.33ms function Ib, genoverse.combined.js line 5
reflow: 0.3ms function .offset, genoverse.combined.js line 6
Unknown property '-moz-border-radius'.  Declaration dropped. tooltips.css:5:53
Error in parsing value for 'cursor'.  Declaration dropped. karyotype.css:40:10
reflow: 0.29ms function Ib, genoverse.combined.js line 5
Error in parsing value for 'background-image'.  Declaration dropped. controlPanel.css:72:20
Error in parsing value for 'background-image'.  Declaration dropped. controlPanel.css:89:20
reflow: 0.3ms function Ib, genoverse.combined.js line 5
reflow: 0.32ms
reflow: 0.53ms
GET 
XHR 
http://rest.ensembl.org/overlap/region/human/13:32198433-32442941 [HTTP/1.1 200 OK 788ms]
reflow: 0.87ms

**Comment by simonbrent** [comment]
Ah, I see what the problem is...you're opening the index.html file (presumably) in Firefox, rather than accessing it via a webserver.

For security reasons, Firefox and Chrome (and probably other browsers, I haven't checked) don't allow cross-site script loading when opening a file in this way. Genoverse relies on jQuery to load some of its components, and jQuery makes the requests for these components in a way that looks like a cross-site script request opening the file in the browser.

The solution is to host the Genoverse code on a webserver, and access it via the address of that webserver. If you don't already have a webserver set up that you can access, the easiest way to do this is to download a program called xampp - https://www.apachefriends.org/index.html

Once this is installed you will need to configure the Apache httpd.conf file, which you can access from the Config button for Apache in xampp's interface. You should search the file for "DocumentRoot" and "<Directory" (they should be one below the other in the file), and change their paths to be wherever you have the Genoverse code on your hard drive, for example:

DocumentRoot "C:/Genoverse"
<Directory "C:/Genoverse">

Once that is done you can start Apache (with the Start button), and then go to localhost in your web browser, where hopefully you will see Genoverse working.

**Comment by jurivero** [comment]
Rocking like a hurricane, That did the work the Apache did it. Thank you very much it is all working like a charmed. Now the next steps .......Build Build Build

**Comment by simonbrent** [comment]
Excellent
