### ISSUE TITLE
Need help to add custom track

### ISSUE THREAD

**Issue by jpofmars** [wtsi-web/Genoverse#28]
Hello,

I would like implementing your genome browser in my web site (made with LARAVEL).
The url used is a script which perform a sql query to get data and return results as json.
I used the parseData function to create feature with start, end and id.
The problem is I'm not able to display the track in the browser, more exactly the track is created but it is empty. The Gene and dbSNP tracks are OK.

Could you help me please ?

Main script :

    var genoverseConfig = {
    container : '#genoverse',
    width    : 1000,
    genome    : 'grch37',
    plugins   : [ 'controlPanel', 'karyotype', 'trackControls', 'resizer', 'focusRegion', 'fullscreen', 'tooltips',     'fileDrop' ],
       tracks    : [
        Genoverse.Track.Scalebar,
       Genoverse.Track.extend({
            name       : 'Sequence',
            controller : Genoverse.Track.Controller.Sequence,
           model      : Genoverse.Track.Model.Sequence.Ensembl,
            view       : Genoverse.Track.View.Sequence,
            100000     : false,
            resizable  : 'auto'
          }),
     Genoverse.Track.Chromosome,
     Genoverse.Track.Gene,
     Genoverse.Track.bacpan,
     Genoverse.Track.dbSNP
      ]
    };
     document.addEventListener('DOMContentLoaded', function () { window.genoverse = new
     Genoverse(genoverseConfig);
     });

js of my custom track.
    
     Genoverse.Track.bacpan = Genoverse.Track.extend({
      id               : 'bacpan',
       name             : 'bacpan',
       info             : 'show cnv from bacpan databases',
       url              : 'http://localhost:8888/select_cnv_browser',
       height : 55,
       bump: true,
       label : true,
       model:Genoverse.Track.Model.extend({
         parseData : function(data){
           for (var i = 0; i < data.length; i++) {
             var feature = data[i];
             var color = '#FFFFFF';
             if (feature["chromosome"] === this.browser.chr){
               // console.log(feature);
               this.insertFeature({
                 start           : feature["hg19_start"],
                 end             : feature["hg19_end"],
                 id              : feature["cnv_id"],
                 label           : feature["cnv_id"],
                 originalFeature : feature
              });
             }
           }
         }
       })
     });

**Comment by zisten** [comment]
In the `insertFeature`, a `chr` data field should be existed in your feature.
```js
{
  chr    : feature["chromosome"],
  start  : feature["hg19_start"],
  end   : feature["hg19_end"],
  id      : feature["cnv_id"],
  label : feature["cnv_id"],
  ...
}
```

BTW, I'm sure you should specify the data by an url filter, eg. `http://localhost:8888/select_cnv_browser?chr=__CHR__&start=__START__&end=__END__`.
Make sure your responce data format is right.

**Comment by jpofmars** [comment]
Thanks for the response.
In fact the problem come from the label. I have given an Integer but it was failed.
I changed it by a string it's ok.
