### ISSUE TITLE
Error when loading VCF

### ISSUE THREAD

**Issue by ponizvezdochka** [wtsi-web/Genoverse#29]
Hello,

I try to add vcf track by drag-n-drop on genoverse website, but track just repeats reference sequence and does not display real SNPs from my vcf. Also, when I click on any SNP, console returns `Cannot read property '0' of undefined`. Can you check, if there is something wrong with vcf parser?

Tried this vcf from ucsc: https://genome.ucsc.edu/goldenPath/help/examples/vcfExampleTwo.vcf

**Comment by simonbrent** [comment]
Thank you for reporting this, I believe I have fixed it now.

**Comment by ponizvezdochka** [comment]
Works like a charm now, thank you!
