### ISSUE TITLE
Wrong reference sequence for GRCh37

### ISSUE THREAD

**Issue by ponizvezdochka** [wtsi-web/Genoverse#30]
Hello,

Just noticed that "Sequence" track shows GRCH38 genome sequence even if I switch to GRCH37 in index.html options:
```
<script type="text/javascript" src="js/genoverse.combined.js">
      {
        container : '#genoverse', // Where to inject Genoverse (css/jQuery selector)
        // If no genome supplied, it must have at least chromosomeSize, e.g.:
        // chromosomeSize : 249250621, // chromosome 1, human
        genome    : 'grch37', // see js/genomes/
```
May be it will be useful to choose genome version in Genoverse.Track.Model.Sequence.Ensembl url like this:
```
Genoverse.Track.Model.Sequence.Ensembl = Genoverse.Track.Model.Sequence.extend({
  url              : '//rest.ensembl.org/sequence/region/human/__CHR__:__START__-__END__?content-type=text/plain;coord_system_version=GRCh37', // Example url
  dataRequestLimit : 10000000 // As per e! REST API restrictions
});
```

Thank you!

**Comment by simonbrent** [comment]
I had not actually realized it was possible to do that - I would have changed the url to //grch37.rest.ensembl.org instead.

Your solution is better though, with a slight modification to allow it to be more configurable:

`
<script type="text/javascript" src="js/genoverse.combined.js">
      {
        container : '#genoverse', // Where to inject Genoverse (css/jQuery selector)
        // If no genome supplied, it must have at least chromosomeSize, e.g.:
        // chromosomeSize : 249250621, // chromosome 1, human
        genome    : 'grch37', // see js/genomes/
        assembly : 'GRCh37',
`

`
Genoverse.Track.Model.Sequence.Ensembl = Genoverse.Track.Model.Sequence.extend({
  url              : '//rest.ensembl.org/sequence/region/human/__CHR__:__START__-__END__?content-type=text/plain;coord_system_version=__ASSEMBLY__', // Example url
  dataRequestLimit : 10000000 // As per e! REST API restrictions
});
`

__ASSEMBLY__ is already supported as an optional parameter when configuring the Genoverse instance.

**Comment by ponizvezdochka** [comment]
Thank you Simon,  __ASSEMBLY__ is much better way!
