### ISSUE TITLE
jQuery.Deferred exception: Cannot read property 'start' of undefined TypeError: Cannot read property 'start' of undefined

### ISSUE THREAD

**Issue by BurkovBA** [wtsi-web/Genoverse#32]
Hi, I'm using Genoverse release 2.4.1 (commit: b46d566f0eca18100336996ab3b8eee1b1339025)

I experience the following error:

```
jQuery.Deferred exception: Cannot read property 'start' of undefined TypeError: Cannot read property 'start' of undefined
```

which happens in `makeFirstImage()` function:
```
      var buffer = this.prop('dataBuffer');

      this.model.getData(start - buffer.start - length, end + buffer.end + length).done(makeImages).fail(function (e) {
        controller.showError(e);
      });
```

Seems, like dataBuffer property is undefined. I'm initializing Genoverse as follows:

```
new Genoverse({
    container: element.find('#genoverse'),
    chr: scope.chromosome,
    species: scope.genome.species,
    showUrlCoords: false, // do not show genomic coordinates in the url
    plugins: ['controlPanel', 'resizer', 'fileDrop'],
         tracks: [
             Genoverse.Track.Scalebar,
             Genoverse.Track.extend({
                 name: 'Sequence',
                 model: configureGenoverseModel('ensemblSequence'),
                 view: Genoverse.Track.View.Sequence,
                 controller: Genoverse.Track.Controller.Sequence,
                 resizable: 'auto',
                 100000: false,
             }),
             Genoverse.Track.extend({
                 name: 'Genes',
                 info: 'Ensembl API genes',
                 labels: true,
                 model: configureGenoverseModel('ensemblGene'),
                 view: Genoverse.Track.View.Gene.Ensembl,
                 controller: Genoverse.Track.Controller.Ensembl,
              }),
              Genoverse.Track.extend({
                  name: 'Transcripts',
                  info: 'Ensembl API transcripts',
                  labels: true,
                  model: configureGenoverseModel('ensemblTranscript'),
                  view: Genoverse.Track.View.Transcript.Ensembl,
                  controller: Genoverse.Track.Controller.Ensembl,
              }),
              Genoverse.Track.extend({
                  name: 'RNAcentral',
                  id: 'RNAcentral',
                  info: 'Unique RNAcentral Sequences',
                  labels: true,
                  model: configureGenoverseModel('rnacentral'),
                  view: Genoverse.Track.View.Transcript.Ensembl,
                  controller: Genoverse.Track.Controller.Ensembl,
              })
          ]
      })
```

where `scope.genome.species` is "Homo Sapiens", `scope.chromosome` is "X", scope.start and scope.stop are reasonable. I'm trying to create an Angular directive, wrapping your code.

Why would that happen?

**Comment by simonbrent** [comment]
Hmm, not sure. Can you show me the code in configureGenoverseModel?

As a side note, you're using a parameter `showUrlCoords` which doesn't exist in Genoverse. You should use `urlParamTemplate: false` instead - this is the supported way to not change the URL based on the location in the browser

**Comment by BurkovBA** [comment]
@simonbrent 

Simon, sorry for late response.

I created a separate repository, [angularjs-genoverse](https://github.com/RNAcentral/angularjs-genoverse), which is an AngularJS (1.x) wrapper for Genoverse - it is meant to be a web-component, that allows you to create and configure the browser, using a declarative HTML syntax. It is also nice because it automatically synchronizes the model with multiple views, so that if you're changing start/end coordinates in one view, all views respond to this. See example: https://RNAcentral.github.io/angularjs-genoverse.

I'm using an old version of Genoverse in that code, forked in 2014 by Anton Petrov. Attempts to replace it with modern ones failed for me with exceptions, described above. Here is full code of Genoverse initialization within it:
https://github.com/RNAcentral/angularjs-genoverse/blob/master/src/genoverse.module.js#L108.

Simon, as we are both working on WTGC, can you spend 30 minutes or so and answer several questions of mine about the design concepts of Genoverse (I'll can get them written by the next week and send them to you beforehand). I'd like to better understand the concepts of Genoverse plugins, callback system with `wrapFunction()`, Genoverse MVC. I'll write down my notes and can submit them to Genoverse documentation - I guess, I'm not the only one to have those questions, right?
