### ISSUE TITLE
width: auto !important; to prevent third-party css from breaking Genoverse

### ISSUE THREAD

**Issue by BurkovBA** [wtsi-web/Genoverse#33]
Please, add `width: auto !important;` line here:

https://github.com/wtsi-web/Genoverse/blob/gh-pages/css/controlPanel.css#L4

Sorry, my repo is forked from simonbrent/Genoverse, so when I create a pull-request to wtsi-web/Genoverse, it carries your edits of documentation from simonbrent/Genoverse with it.
So, I'm posting this as an issue.

Thanks a lot, again!

**Comment by BurkovBA** [comment]
Though, I have to say, this is not a good solution, cause now `td.gv-canvas-container` is constantly having a width of 942 pixels and I can't make Genoverse fit into screens smaller than 1200 px or so.

**Comment by pdl** [comment]
I'm not sure what third-party css is breaking Genoverse and how and from the viable comments, it appears that the solution proposed is not viable either.
