### ISSUE TITLE
Genoverse popup uncloseable

### ISSUE THREAD

**Issue by stefanches7** [wtsi-web/Genoverse#35]
"close" button gets rendered outside of the screen. Scaling won't help.
![genoverse-popup-bug](https://cloud.githubusercontent.com/assets/17748742/25996170/231530e8-3716-11e7-8fe4-8fe3bb6ba669.PNG)

**Comment by simonbrent** [comment]
There is now an internal scrollbar on these popups, so this issue no longer occurs
