### ISSUE TITLE
Track available but not displayed

### ISSUE THREAD

**Issue by jpofmars** [wtsi-web/Genoverse#36]
Hi everybody.

first thanks for this great browser. It is the best for me.
I would like to put tracks as available and to not displayed its in my browser.
How can I do that ?

Thanks

**Comment by simonbrent** [comment]
You can do this using the `tracksLibrary` property, as follows:
```
new Genoverse({
  .... your config ....
  tracksLibrary: [ 
    Genoverse.Track.extend({ ... track1 conf ... }),
    Genoverse.Track.extend({ ... track2 conf ... }),
    ... all available tracks ...
  ],
  tracks: [
    tracksLibrary[0],
    tracksLibrary[1],
    ... all initially displayed tracks ...
  ]
});
```
You can have tracks which aren't in the tracksLibrary, but if a user removes these they will not be able to add them again, so it's not advisable.

The exception to this is that any track that doesn't have a `name` property (e.g. the scalebar) will not appear in the list of tracks that can be added and removed.

**Comment by jpofmars** [comment]
Thank you !
That works fine.
