### ISSUE TITLE
Hide tracks by default

### ISSUE THREAD

**Issue by ens-lgil** [wtsi-web/Genoverse#41]
Hi,

Is it possible to make a track available in the "Tracks" menu but hide it by default ?
i.e. I want to have the dbSNP track available in the menu but I would like this track to be hidden when I load the Genoverse widget.

Thanks,

Laurent

**Comment by simonbrent** [comment]
Yes - see here: https://github.com/wtsi-web/Genoverse/issues/36

**Comment by ens-lgil** [comment]
Great!
Thank you Simon!
