### ISSUE TITLE
jquery-ui clashes with d3 for mouseup event

### ISSUE THREAD

**Issue by BurkovBA** [wtsi-web/Genoverse#44]
If you have genoverse on a page, running at the same time with d3, jquery-ui in genoverse will break d3 mouseup events - e.g. your d3 brushes will stop emitting brushend event, your selections will never be closed and zooms won't work.

To reproduce, try a page with both Genoverse and some d3 plugin (such as[ feature-viewer](https://github.com/calipho-sib/feature-viewer) or [fornac](https://github.com/pkerpedjiev/fornac)) and with d3 only. Open Chrome Developer Tools, go to Event Listener Breakpoints and try settings a breakpoint to mouseup - you'll find out that d3's `brushend` event is fired when Genoverse is not displayed, but is not fired, when Genoverse is displayed.

**Comment by simonbrent** [comment]
Thank you SO much for this - we are having a similar problem and would not have thought of this conflict as a cause

**Comment by simonbrent** [comment]
Should now be fixed: https://github.com/wtsi-web/Genoverse/commit/878e1495a63dbce964cb99e5cbde97950f092f57

That code was really stupid (and not written by me!)

**Comment by BurkovBA** [comment]
Aha, so this is not jquery-ui, this is funky event handler in Genoverse itself. 

Thanks a lot for quick response, Simon - I thought, I'll spend the whole day in the debugger today.
