### ISSUE TITLE
Can you make a bundle without jquery and other standard dependencies, available via npm?

### ISSUE THREAD

**Issue by BurkovBA** [wtsi-web/Genoverse#45]
Unfortunately, Genoverse bundle conflicts with other instances of jquery (so can do other libraries in Genoverse bundle) that I have in the project. Can you do a version of bundle with Genoverse and its modules only and specify required libraries in npm dependencies section?

I saw some Webpack files in newer version of Genoverse. I wanted to mention that Webpack is not suitable for libraries distribution - it's meant for website distribution. For bundling libraries, they usually use some `npm script/gulp/grunt` chain of commands. For libraries they also recommend [Rollup](https://medium.com/webpack/webpack-and-rollup-the-same-but-different-a41ad427058c), especially, if it's in ECMA6.

Thanks and cheers!

**Comment by simonbrent** [comment]
Genoverse is not ES2015 (or for that matter, any other nice recent package management-compatible style), so I can't use Rollup.

I'm afraid I don't have a good solution for you at the moment. I would suggest using the unminified code, selecting which tracks/plugins you care about, and then building your own single Genoverse file in the manner of your choosing.

**Comment by simonbrent** [comment]
Ok, I've decided to go a different way on this. Instead of providing a version without jquery, and then have people's builds potentially break because of unresolved peer dependencies or version differences, I've created a version of Genoverse which internalizes jquery using $.noConfilct(true). Please try it out and let me know if it works for you:

https://github.com/wtsi-web/Genoverse/tree/internal-jquery

If you want to access Genoverse's at any time, use Genoverse.$jq.
Tracks/controllers/models/views additionally have this available as this.$jq.

**Comment by BurkovBA** [comment]
Hi, Simon, sorry for late response. 

This is not a bad solution, but right away I expect the following problem:

```
<html>
  <head>
  </head>
  <body>
    <script src="http://code.jquery.com/jquery-3.3.1.js" integrity="sha256-2Kok7MbOyxpgUVvAk/HJ2jigOSYS2auK4Pfzbm7uH60=" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-1.12.4.min.js" integrity="sha256-ZosEbRLbNQzLpnKIkEdrPv7lOy9C27hHQ+Xp8a4MxAQ=" crossorigin="anonymous"></script>
    <script>
      $.noConflict();
    </script>
    <script>
      console.log($.fn.jquery);
      console.log(jQuery.fn.jquery);
    </script>
  </body>
</html>
```

Result: 
```
test.html:11 3.3.1
test.html:12 1.12.4
```

**Comment by simonbrent** [comment]
As I said in the previous comment, I'm using `noConflict(true)`, which relinquishes both `$` and `jQuery`. Try it and see.

**Comment by BurkovBA** [comment]
Indeed, it works with `noConflict(true)`. Thanks for notification, Simon, I'll test it next week and come back to you.

**Comment by simonbrent** [comment]
Closing due to over 3 years of inactivity
