### ISSUE TITLE
Convert highlights to histogram

### ISSUE THREAD

**Issue by alisha2468** [wtsi-web/Genoverse#49]
I am trying to change the SNV display highlights to histogram form. Any help would be appreciated. Thanks!

**Comment by simonbrent** [comment]
I don't really understand what you're trying to do.

**Comment by alisha2468** [comment]
Hi simon,

When you drag and drop a vcf file into the genome browser, a new track is generated showing the SNVs at each position. I want to generate histograms of SNP density at each position instead

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by simonbrent** [comment]
I'm afraid that isn't really possible at this time. I would recommend creating a back-end process that reads the VCF and outputs data as required by Genoverse.Track.Graph.Bar, but that won't really help with the drad and drop use case.

**Comment by alisha2468** [comment]
Thank you Simon! If possible, could you give me an example please?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by simonbrent** [comment]
Not really...you'll need a VCF parser (like bcftools), a web server written in the language of your choice which 
a) can accept VCF uploads/extract data from URLs where VCFs are stored
b) has an endpoint that extracts data from a VCF for a region it and returns a JSON array where each entry is in the form { chr: 1, start: 100, end: 100, height: 5 } // height = the number of variants found at that location

**Comment by alisha2468** [comment]
Hi Simon, 
I tried parsing the VCF but it does not work when extended from Graph.Bar or Graph.Line but works otherwise. Any idea why that is happening?
