### ISSUE TITLE
ScatterPlots?

### ISSUE THREAD

**Issue by mattjvincent** [wtsi-web/Genoverse#68]
Any plans on developing a Scatter Plot Track?

Thanks!

Matt

**Comment by simonbrent** [comment]
Hi Matt,

Development only really takes place when features are needed for my full-time job on [DECIPHER ](https://www.deciphergenomics.org/), and we have no need for a scatter plot track at this time.

Genoverse does currently support bar and line graphs, so it should be possible to extend `Genoverse.Track.Graph` in such a way that it draws points instead, but I don't have the time to do so right now.
