### ISSUE TITLE
Wiggle Support

### ISSUE THREAD

**Issue by andrewyatz** [wtsi-web/Genoverse#9]
It would be great if genoverse could support continuous data sets such as those found in wig files. Ideally supporting:
- line drawing
- bar charts

I would really like to see support for the following (but they can be pushed into separate issues once the basic support is there):
- configurable axis/cut-offs
- set a cut-off but just draw a line across to highlight the outliers
- log rendering
- support more than 1 wiggle data set in a single track

**Comment by sourabh2k15** [comment]
I have started by understanding the wig format from here : https://genome.ucsc.edu/goldenpath/help/wiggle.html , after doing so I will try writing a JS module that can visualize data in wig files in line drawing.

**Comment by simonbrent** [comment]
Line drawing is now done (https://github.com/wtsi-web/Genoverse/blob/gh-pages/js/Track/library/LineGraph.js) although there is no log rendering at this point.

I plan to add bar charts in the near future by creating a shared parent for line and bar for axis/y scaling etc.
